import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { applyPenguinIceAction, calculatePenguinIceResult, PENGUIN_ICE_STAGES, startPenguinIce, type PenguinIceState } from '../../features/penguin-ice/model/penguinIce'
import { markGameCleared } from '../../features/clear-progress/model/clearProgressStorage'
import { PageLayout } from '../../shared/components/PageLayout'

const adjacent = (index: number) => { const r = Math.floor(index / 4); const c = index % 4; return [[r - 1, c], [r + 1, c], [r, c - 1], [r, c + 1]].filter(([y, x]) => y >= 0 && y < 4 && x >= 0 && x < 4).map(([y, x]) => y * 4 + x) }

export function PenguinIcePage({ storage, initialState }: { storage?: Storage; initialState?: PenguinIceState } = {}) {
  const [game, setGame] = useState<PenguinIceState | null>(initialState ?? null); const [feedback, setFeedback] = useState('ひかっている となりの こおりへ！'); const recorded = useRef(false)
  const result = useMemo(() => game?.status === 'finished' ? calculatePenguinIceResult(game) : null, [game])
  useEffect(() => { if (result?.isCleared && !recorded.current) { recorded.current = true; markGameCleared('penguin-ice', storage) } }, [result, storage])
  const begin = () => { recorded.current = false; setGame(startPenguinIce()); setFeedback('ひかっている となりの こおりへ！') }
  const act = (action: Parameters<typeof applyPenguinIceAction>[1]) => { if (!game) return; const t = applyPenguinIceAction(game, action); if (t.events.some(e => e.type === 'stage-won')) setFeedback('ペンギンの かち！'); else if (t.events.some(e => e.type === 'stage-lost')) setFeedback('アザラシに まけちゃった！'); else if (t.events.some(e => e.type === 'player-moved')) setFeedback('さかな ゲット！ つぎの こおりは？'); setGame(t.state) }
  if (!game) return <PageLayout title="ペンギン こおりとり"><div className="penguin-ice-center"><div className="penguin-ice-scene">🐧 🧊🐟 🧊🐟🐟 🦭</div><p>となりの こおりへ すすんで さかなを あつめよう。アザラシより おおく とれるかな？</p><button className="primary-button" onClick={begin}>こおりの しまへ</button><Link to="/play">あそびへ戻る</Link></div></PageLayout>
  if (result) return <PageLayout title="ペンギン こおりとり"><div className="penguin-ice-center"><div className="penguin-ice-scene">🐧🐟✨🏆✨🐟</div><h2>こおりとり マスター！</h2><p className="penguin-ice-score">{result.score} てん</p><button className="primary-button" onClick={begin}>もういちど</button><Link to="/play">あそびへ戻る</Link></div></PageLayout>
  const stage = PENGUIN_ICE_STAGES[game.stageIndex]; const moves = adjacent(game.playerIndex); const over = game.status !== 'playing'
  return <PageLayout title="ペンギン こおりとり"><div className="penguin-ice-center"><div className="penguin-ice-hud"><span>🏝️ {game.stageIndex + 1} / {PENGUIN_ICE_STAGES.length}</span><span>🐧 🐟{game.playerScore}</span><span>🦭 🐟{game.rivalScore}</span><span>👣 {game.turn} / 5</span></div><b>{stage.name}</b><div className="penguin-ice-board" role="grid" aria-label="こおりの しま">{stage.fish.map((fish, index) => { const claimed = game.claimed.includes(index); const player = index === game.playerIndex; const rival = index === game.rivalIndex; const canMove = !over && moves.includes(index) && !claimed && !rival; return <button key={index} aria-label={`こおり ${index + 1}、さかな ${fish}ひき`} disabled={!canMove} className={`penguin-ice-floe${claimed && !player && !rival ? ' penguin-ice-floe--water' : ''}${canMove ? ' penguin-ice-floe--reachable' : ''}`} onClick={() => act({ type: 'move', index })}><span aria-hidden="true">{player ? '🐧' : rival ? '🦭' : claimed ? '🌊' : '🧊'}</span>{!claimed && <small aria-hidden="true">{'🐟'.repeat(fish)}</small>}</button> })}</div><p className="penguin-ice-feedback">{feedback}</p>{game.status === 'stage-won' && <section className="penguin-ice-finish"><h2>ペンギンの かち！</h2><p>🐧 {game.playerScore} − {game.rivalScore} 🦭</p><button className="primary-button" onClick={() => act({ type: 'next-stage' })}>つぎの しま</button></section>}{game.status === 'failed' && <section className="penguin-ice-finish"><h2>おしい！</h2><p>🐧 {game.playerScore} − {game.rivalScore} 🦭</p><button className="primary-button" onClick={() => act({ type: 'retry' })}>もういちど しょうぶ</button></section>}<button className="penguin-ice-quit" onClick={() => setGame(null)}>しまを でる</button></div></PageLayout>
}
