import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { applyShapeCatcherAction, calculateShapeCatcherResult, SHAPE_CATCHER_STAGES, startShapeCatcher, type ShapeCatcherState, type ShapeKind } from '../../features/shape-catcher/model/shapeCatcher'
import { markGameCleared } from '../../features/clear-progress/model/clearProgressStorage'
import { PageLayout } from '../../shared/components/PageLayout'

const glyphs: Record<ShapeKind, string> = { bar: '▬', corner: '⌟', tee: '⊥' }
const names: Record<ShapeKind, string> = { bar: 'ぼう', corner: 'かど', tee: 'Tがた' }

export function ShapeCatcherPage({ storage, initialState }: { storage?: Storage; initialState?: ShapeCatcherState } = {}) {
  const [game, setGame] = useState<ShapeCatcherState | null>(initialState ?? null); const [feedback, setFeedback] = useState('おなじ むきの うけざらを つくろう！'); const recorded = useRef(false)
  const result = useMemo(() => game?.status === 'finished' ? calculateShapeCatcherResult(game) : null, [game])
  useEffect(() => { if (result?.isCleared && !recorded.current) { recorded.current = true; markGameCleared('shape-catcher', storage) } }, [result, storage])
  useEffect(() => { if (!game || game.status !== 'playing') return; const stage = SHAPE_CATCHER_STAGES[game.stageIndex]; const timer = window.setInterval(() => setGame(current => { if (!current || current.status !== 'playing') return current; const t = applyShapeCatcherAction(current, { type: 'tick' }); if (t.events.some(e => e.type === 'caught')) setFeedback('✨ ぴったり キャッチ！'); else if (t.events.some(e => e.type === 'missed')) setFeedback('💨 むきが ちがった！'); return t.state }), stage.intervalMs); return () => window.clearInterval(timer) }, [game?.stageIndex, game?.status])
  const begin = () => { recorded.current = false; setGame(startShapeCatcher()); setFeedback('おなじ むきの うけざらを つくろう！') }
  const act = (action: Parameters<typeof applyShapeCatcherAction>[1]) => { if (!game) return; const t = applyShapeCatcherAction(game, action); if (action.type === 'rotate') setFeedback(`${names[action.kind]}を くるっ！`); else setFeedback('つぎの かたちを みよう！'); setGame(t.state) }
  if (!game) return <PageLayout title="くるくる かたちキャッチ"><div className="shape-catcher-center shape-catcher-intro"><div className="shape-catcher-scene">▬　⌟　⊥</div><p>おちてくる かたちに あわせて、うけざらを くるくる まわそう！</p><button className="primary-button" onClick={begin}>キャッチ スタート！</button><Link to="/play">あそびへ戻る</Link></div></PageLayout>
  if (result) return <PageLayout title="くるくる かたちキャッチ"><div className="shape-catcher-center shape-catcher-intro"><div className="shape-catcher-scene">▬⌟⊥✨🏆</div><h2>かたちキャッチ マスター！</h2><p className="shape-catcher-score">⭐ {result.stars}こ　{result.score}てん</p><p>さいこう {result.bestCombo} コンボ！</p><button className="primary-button" onClick={begin}>もういちど</button><Link to="/play">あそびへ戻る</Link></div></PageLayout>
  const stage = SHAPE_CATCHER_STAGES[game.stageIndex]; const piece = stage.pieces[Math.min(game.pieceIndex, stage.pieces.length - 1)]; const top = 8 + (1 - game.fall / stage.dropTicks) * 48
  return <PageLayout title="くるくる かたちキャッチ"><div className="shape-catcher-center"><div className="shape-catcher-hud"><span>🧺 {game.stageIndex + 1} / 4</span><span>{'❤️'.repeat(Math.max(0, game.hearts))}</span><span>📦 {game.pieceIndex} / {stage.pieces.length}</span><span>🔥 {game.combo}</span></div><b>{stage.name}</b><div className="shape-catcher-field"><div className="shape-catcher-falling" style={{ top: `${top}%`, transform: `translateX(-50%) rotate(${piece.rotation * 90}deg)` }}>{glyphs[piece.kind]}</div><div className="shape-catcher-bins">{(['bar', 'corner', 'tee'] as const).map(kind => <button key={kind} aria-label={`${names[kind]}の うけざらを まわす`} data-rotation={game.rotations[kind]} disabled={game.status !== 'playing'} onClick={() => act({ type: 'rotate', kind })}><span style={{ transform: `rotate(${game.rotations[kind] * 90}deg)` }}>{glyphs[kind]}</span><small>{names[kind]} ↻</small></button>)}</div></div><p className="shape-catcher-feedback">{feedback}</p>{game.status === 'stage-won' && <section className="shape-catcher-finish"><h2>ぜんぶ キャッチ！</h2><p>{'⭐'.repeat(game.stageStars)}</p><button className="primary-button" onClick={() => act({ type: 'next-stage' })}>つぎの ステージ</button></section>}{game.status === 'failed' && <section className="shape-catcher-finish"><h2>おしい！</h2><button className="primary-button" onClick={() => act({ type: 'retry' })}>もういちど</button></section>}<button className="shape-catcher-quit" onClick={() => setGame(null)}>こうじょうを でる</button></div></PageLayout>
}
